[workspace]
resolver = "1"

members = [
  "lifetime",
  "boxref",
  "rc",
  "cell",
  "thread",
  "future",
  "my-redis",
  "future-time",
  "future-pin",
  "future-stream",
  "pin-mark",
  "future-channel",
  "yew-await",
]
