[package]
name = "pin-mark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project = "1.1.3"
pin-project-lite = "0.2.13"
pin-utils = "0.1.0"
